---
abstract: 'Provides Lvalue accessors to Moo class attributes'
author:
  - "Damien \"dams\" Krotkine"
build_requires:
  Module::Build: 0.3601
  Test::Most: 0
  Test::Pretty: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooX-LvalueAttribute
provides:
  Method::Generate::Accessor::Role::LvalueAttribute:
    file: lib/Method/Generate/Accessor/Role/LvalueAttribute.pm
    version: 0.12
  MooX::LvalueAttribute:
    file: lib/MooX/LvalueAttribute.pm
    version: 0.12
requires:
  Hash::Util::FieldHash::Compat: 0
  Moo: 1.000008
  Variable::Magic: 0.52
  strictures: 1
resources:
  repository: git://github.com/dams/MooX-LvalueAttribute.git
version: 0.12
